[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps"

[
context.production
]
  environment = { NODE_ENV = "production" }

[
context.deploy-preview
]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

