[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10.8.2"
  CI = "false"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[dev]

framework = "vite"
targetPort = 5173

[[
redirects
]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add proper MIME type headers
[[headers]]
  for = "/assets/*.js"
[headers.values]
  Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  
[headers.values]
  Content-Type = "text/css"


[[headers]]
  for = "/*"

[headers.vaules]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"